# Generated by Django 3.1.7 on 2021-04-18 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('categories', '0001_initial'),
        ('books', '0008_auto_20210415_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='authors.authormodel'),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='categories.categorymodel'),
        ),
        migrations.DeleteModel(
            name='AuthorModel',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
