# Generated by Django 3.1.7 on 2021-04-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20210418_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers'),
        ),
    ]
